# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: 'pre-push checklist (test, typecheck, etc.)'
    cmds:
      - task: test
      - task: typecheck
      - task: lint
        vars: { FIX: '{{.FIX}}' }
      - task: fmt
    silent: true
  fix:
    desc: 'pre-push checklist, with ruff autofixing what it can'
    cmds:
      - task: default
        vars: { FIX: '--fix' }
    silent: true
  test:
    desc: 'run pytest suite'
    cmds:
      - uv run pytest
  typecheck:
    desc: 'run basedpyright type checking'
    cmds:
      - uv run basedpyright
  lint:
    desc: 'run ruff linter (pass FIX=--fix to autofix)'
    cmds:
      - uv run ruff check {{.FIX}}
  fmt:
    desc: 'run ruff code formatting'
    cmds:
      - uv run ruff format
