# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: "pre-push checklist (test, typecheck, etc.)"
    cmds:
      - task: test
      - task: typecheck
      - task: lint
      - task: fmt
    silent: true
  test:
    desc: "run pytest suite"
    cmds:
      - uv run pytest
  typecheck:
    desc: "run pyright type checking"
    cmds:
      - uv run pyright
  lint:
    desc: "run ruff linter"
    cmds:
      - uv run ruff check
  fmt:
    desc: "run ruff code formatting"
    cmds:
      - uv run ruff format
